
#ifndef HOBBES_LANG_TYPEPREDS_HPP_INCLUDED
#define HOBBES_LANG_TYPEPREDS_HPP_INCLUDED

#include <hobbes/lang/type.H>
#include <hobbes/lang/expr.H>
#include <hobbes/lang/typeinf.H>

// import all type predicate schemes
#include <hobbes/lang/preds/packsto.H>
#include <hobbes/lang/preds/class.H>
#include <hobbes/lang/preds/subtype.H>
#include <hobbes/lang/preds/hasfield.H>
#include <hobbes/lang/preds/hasctor.H>
#include <hobbes/lang/preds/appendsto.H>
#include <hobbes/lang/preds/consrecord.H>
#include <hobbes/lang/preds/consvariant.H>
#include <hobbes/lang/preds/vapp.H>
#include <hobbes/lang/preds/equal.H>
#include <hobbes/lang/preds/not.H>
#include <hobbes/lang/preds/recty.H>
#include <hobbes/lang/preds/str.H>
#include <hobbes/lang/preds/deconstruct.H>
#include <hobbes/lang/preds/data.H>
#include <hobbes/lang/preds/typeof.H>
#include <hobbes/lang/preds/sizeof.H>
#include <hobbes/ipc/process.H>

#endif

