#line 2 "hexpr.lex.C"

#line 4 "hexpr.lex.C"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 122
#define YY_END_OF_BUFFER 123
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[282] =
    {   0,
        0,    0,    0,    0,  123,  121,    2,    1,    2,    2,
       40,  121,  121,   86,   78,   89,   64,   65,   76,   74,
       71,   75,   82,   77,  101,  101,   30,   72,   36,   26,
       38,   87,   85,   93,   93,   93,   66,   79,   67,   84,
       90,   93,   93,   93,   93,   93,   93,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   68,   70,   69,   34,
       13,   12,   13,    7,    5,    8,    6,    0,   35,    0,
      102,    0,    0,    0,    0,   73,   31,   83,    0,   10,
        0,    0,  101,   98,   99,  100,    0,  108,  107,  106,
      105,    0,    0,   27,   29,   25,   37,   32,   28,   39,

       93,   93,   93,   93,   93,   93,   93,   93,   60,   93,
       93,   93,   80,   52,   93,   57,   93,   93,   93,   93,
       49,   93,   51,   93,   93,   93,   93,   93,   93,   93,
       93,    0,   11,    3,    0,    0,   81,    0,  102,    0,
       63,   88,    0,    0,    9,   96,  101,    0,    0,    0,
        0,    0,  103,  104,    0,   33,   93,   93,   50,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   42,   93,
       93,   41,   93,   93,   93,   93,   93,   93,   93,   93,
       93,   93,   62,    4,   94,   97,   95,  101,    0,   91,
      111,    0,  109,   92,   24,   93,   43,   93,   19,   93,

       54,   93,   93,   93,   93,   93,   93,   93,   58,   93,
       93,   53,   55,   18,   93,   93,   48,    0,  101,  112,
      110,   93,   20,   93,   93,   56,   93,   93,   45,   93,
       93,   47,   93,   93,   16,    0,    0,   23,   93,   22,
       17,   93,   93,   15,   14,   61,   59,    0,    0,   44,
       93,   46,    0,  113,   21,    0,    0,  116,    0,    0,
        0,    0,  114,    0,    0,    0,    0,    0,  115,  117,
        0,    0,  118,    0,    0,    0,  119,    0,    0,  120,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    9,   10,   11,    1,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   31,   31,   32,   33,
       34,   35,   34,   34,   34,   36,   34,   37,   34,   34,
       34,   34,   38,   39,   40,   34,   34,   41,   34,   34,
       42,   43,   44,   45,   34,   46,   47,   31,   48,   49,

       50,   51,   34,   52,   53,   34,   54,   55,   56,   57,
       58,   59,   34,   60,   61,   62,   63,   34,   64,   65,
       66,   34,   67,   68,   69,   70,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[71] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    1,    1,    4,    1,    1,    1,    1,    4,
        5,    5,    1,    1,    1,    1,    1,    1,    1,    5,
        5,    5,    5,    6,    6,    6,    6,    6,    6,    6,
        6,    1,    1,    1,    1,    1,    5,    5,    5,    5,
        5,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[294] =
    {   0,
        0,    0,   68,   69,  392,  393,  393,   71,   72,  372,
      364,   67,  371,  393,  393,  345,  393,  393,  393,  371,
      393,  359,   60,   65,   92,   35,   63,  393,   69,   64,
      359,  393,  393,    0,  354,  346,  393,  393,  393,  393,
      393,  325,   41,   47,   37,   46,   50,  331,   51,  322,
       57,  332,  328,   52,  320,   67,  358,  393,  393,  393,
      393,  393,  355,  119,  120,  393,  393,  368,  393,   91,
      393,  121,  304,  103,  360,  393,  393,  393,  116,  393,
      368,  110,  128,  393,  393,  393,    0,  323,  311,   99,
      393,  307,    0,  393,  393,  393,  393,  341,  393,  393,

        0,  333,  327,  315,  302,  315,  299,  309,    0,  298,
      305,  302,    0,    0,  297,  294,  292,  291,  303,  289,
        0,  288,    0,   94,  287,  298,  284,  287,  286,  294,
      281,  333,  393,  393,  156,    0,  393,  128,  135,  153,
      393,  393,  144,  338,  393,  152,  158,  146,    0,  274,
      276,  281,  393,  393,    0,  393,  305,  306,    0,  285,
      273,  286,  285,  281,  269,  268,  270,  265,    0,  278,
      262,    0,  271,  269,  261,  258,  263,  269,  268,  270,
      256,  263,  393,  393,  161,  393,  393,  166,  168,  393,
      393,  254,  393,    0,    0,  280,    0,  251,    0,  248,

        0,  248,  259,  248,  260,  254,  250,  246,    0,  253,
      242,    0,    0,    0,  253,  250,    0,  170,  281,  275,
      393,  265,    0,  241,  234,    0,  232,  236,  242,  241,
      233,    0,  232,  234,    0,  173,  176,    0,  225,    0,
        0,  238,  222,    0,    0,    0,    0,  245,  178,    0,
      206,    0,  180,  236,    0,  183,  185,  147,  187,  189,
      191,  193,  195,  154,  197,  199,  201,  203,  393,  152,
      205,  207,  153,  209,  211,  213,  215,  217,  219,  393,
      393,  241,  247,  253,  255,  261,  267,  273,  165,  154,
      279,  140,  118

    } ;

static const flex_int16_t yy_def[294] =
    {   0,
      281,    1,  282,  282,  281,  281,  281,  281,  281,  281,
      281,  283,  281,  281,  281,  284,  281,  281,  281,  281,
      281,  281,  281,  281,  281,   25,  281,  281,  281,  281,
      281,  281,  281,  285,  285,  285,  281,  281,  281,  281,
      281,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  281,  281,  281,  281,
      281,  281,  281,  286,  286,  281,  281,  281,  281,  283,
      281,  287,  281,  284,  284,  281,  281,  281,  281,  281,
      288,  281,   25,  281,  281,  281,  289,  281,  281,  281,
      281,  281,  290,  281,  281,  281,  281,  281,  281,  281,

      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  281,  281,  281,  286,  291,  281,  283,  283,  287,
      281,  281,  281,  288,  281,  281,   83,  281,  292,  281,
      281,  281,  281,  281,  293,  281,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  281,  281,  281,  281,  281,  147,  281,  281,
      281,  281,  281,  290,  285,  285,  285,  285,  285,  285,

      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  281,  188,  281,
      281,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  285,  285,  281,  281,  285,  285,  285,
      285,  285,  285,  285,  285,  285,  285,  281,  281,  285,
      285,  285,  281,  281,  285,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
        0,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281

    } ;

static const flex_int16_t yy_nxt[464] =
    {   0,
        6,    7,    8,    7,    9,   10,   11,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       34,   34,   34,   34,   34,   34,   34,   35,   34,   36,
       34,   37,   38,   39,   40,   41,   42,   43,   44,   45,
       46,   34,   47,   34,   48,   49,   50,   51,   52,   53,
       34,   54,   55,   56,   34,   34,   57,   58,   59,   60,
       62,   62,   64,   66,   71,  281,   65,   67,   78,   80,
       79,   79,   63,   63,   81,   94,   96,  105,   95,   98,
       99,  110,  112,  107,   97,  106,  108,  118,   71,  281,

      114,  111,  113,  126,  109,  115,  116,  121,  119,   72,
       82,  127,   83,   83,  142,  122,  123,  128,  130,  131,
      135,  135,  194,   70,  135,  135,   84,   85,  139,   86,
      146,  146,   87,   72,  143,   71,   79,   79,  136,  136,
       88,  174,   71,   89,  190,   75,   85,   90,  147,  147,
      148,  152,   91,  175,   92,   70,   93,  135,  155,  153,
      139,  135,  186,  140,  185,  185,  189,  189,  281,  149,
       72,  274,  146,  146,  271,  136,  266,   72,  188,  188,
      281,  185,  185,  218,  187,  260,  219,  219,  220,  220,
      236,  236,  281,  248,  248,  140,  249,  249,  254,  254,

      256,  256,  187,  258,  258,  259,  259,  261,  261,  262,
      262,  263,  263,  264,  264,  265,  265,  267,  267,  268,
      268,  269,  269,  270,  270,  272,  272,  273,  273,  275,
      275,  276,  276,  277,  277,  278,  278,  279,  279,  280,
      280,   61,   61,   61,   61,   61,   61,   70,   70,   70,
       70,   70,   70,   74,  257,  255,   74,   74,   74,  101,
      101,  134,  253,  134,  134,  134,  134,  138,  138,  138,
      138,  138,  138,  144,  144,  144,  144,  144,  144,  184,
      184,  184,  252,  184,  184,  251,  250,  247,  246,  245,
      244,  243,  242,  241,  240,  239,  238,  237,  281,  235,

      234,  233,  232,  231,  230,  229,  228,  227,  226,  225,
      224,  223,  222,  221,  217,  216,  215,  214,  213,  212,
      211,  210,  209,  208,  207,  206,  205,  204,  203,  202,
      201,  200,  199,  198,  197,  196,  195,  193,  192,  191,
      145,  183,  182,  181,  180,  179,  178,  177,  176,  173,
      172,  171,  170,  169,  168,  167,  166,  165,  164,  163,
      162,  161,  160,  159,  158,  157,  156,  154,  151,  150,
      145,   74,  141,  137,  133,  132,  129,  125,  124,  120,
      117,  104,  103,  102,  100,   77,   76,   75,   73,   69,
       68,  281,    5,  281,  281,  281,  281,  281,  281,  281,

      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281
    } ;

static const flex_int16_t yy_chk[464] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    4,    8,    9,   12,   26,    8,    9,   23,   24,
       23,   23,    3,    4,   24,   27,   29,   43,   27,   30,
       30,   45,   46,   44,   29,   43,   44,   49,   70,   26,

       47,   45,   46,   54,   44,   47,   47,   51,   49,   12,
       25,   54,   25,   25,   74,   51,   51,   54,   56,   56,
       64,   65,  293,   72,   64,   65,   25,   25,   72,   25,
       82,   82,   25,   70,   79,  138,   79,   79,   64,   65,
       25,  124,  139,   25,  292,   74,   25,   25,   83,   83,
       83,   90,   25,  124,   25,  140,   25,  135,  290,   90,
      140,  135,  146,   72,  143,  143,  148,  148,   83,  289,
      138,  273,  146,  146,  270,  135,  264,  139,  147,  147,
      147,  185,  185,  188,  146,  258,  188,  188,  189,  189,
      218,  218,   83,  236,  236,  140,  237,  237,  249,  249,

      253,  253,  146,  256,  256,  257,  257,  259,  259,  260,
      260,  261,  261,  262,  262,  263,  263,  265,  265,  266,
      266,  267,  267,  268,  268,  271,  271,  272,  272,  274,
      274,  275,  275,  276,  276,  277,  277,  278,  278,  279,
      279,  282,  282,  282,  282,  282,  282,  283,  283,  283,
      283,  283,  283,  284,  254,  251,  284,  284,  284,  285,
      285,  286,  248,  286,  286,  286,  286,  287,  287,  287,
      287,  287,  287,  288,  288,  288,  288,  288,  288,  291,
      291,  291,  243,  291,  291,  242,  239,  234,  233,  231,
      230,  229,  228,  227,  225,  224,  222,  220,  219,  216,

      215,  211,  210,  208,  207,  206,  205,  204,  203,  202,
      200,  198,  196,  192,  182,  181,  180,  179,  178,  177,
      176,  175,  174,  173,  171,  170,  168,  167,  166,  165,
      164,  163,  162,  161,  160,  158,  157,  152,  151,  150,
      144,  132,  131,  130,  129,  128,  127,  126,  125,  122,
      120,  119,  118,  117,  116,  115,  112,  111,  110,  108,
      107,  106,  105,  104,  103,  102,   98,   92,   89,   88,
       81,   75,   73,   68,   63,   57,   55,   53,   52,   50,
       48,   42,   36,   35,   31,   22,   20,   16,   13,   11,
       10,    5,  281,  281,  281,  281,  281,  281,  281,  281,

      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  281,
      281,  281,  281
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[123] =
    {   0,
1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "hexpr.l"
#line 2 "hexpr.l"
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wold-style-cast"

int yycolumn = 1;

#define YY_NO_INPUT
#define YY_USER_ACTION \
  yylloc.first_line = yylloc.last_line = yylineno; \
  yylloc.first_column = yycolumn; yylloc.last_column = yycolumn+yyleng-1; \
  yycolumn += yyleng;

#include <hobbes/lang/module.H>
#include <hobbes/lang/expr.H>
#include <hobbes/lang/pat/pattern.H>
#include <hobbes/util/autorelease.H>
#include <hobbes/util/stream.H>
#include <hobbes/parse/grammar.H>
#include <hobbes/read/pgen/hexpr.parse.H>
#include <limits>
#include <string>
#include <iostream>

namespace {
std::out_of_range make_err(const std::string& s) {
  return std::out_of_range(std::string("literal ") + s + " is not supported");
}

int str2int(const std::string& s) {
  try {
    return std::stoi(s);
  } catch (const std::out_of_range&) {
    throw make_err(s);
  }
}

long str2long(const std::string& s) {
  try {
    return std::stol(s);
  } catch (const std::out_of_range&) {
    throw make_err(s);
  }
}

short str2short(const std::string& s) {
  const auto i = str2int(s);
  if (i > std::numeric_limits<short>::max()) {
    throw make_err(s);
  }
  return static_cast<short>(i);
}

__int128 str2int128(const std::string& s) {
  __int128 i = 0;
  if (!readInt128(s, &i)) {
    throw make_err(s);
  }
  return i;
}
}

#define SAVE_STR    yylval.string = hobbes::autorelease(new std::string(yytext, yytext + yyleng))
#define SAVE_IDENT  yylval.string = identifier(yytext, yytext + yyleng)
#define SAVE_BOOL   std::istringstream(std::string(yytext, yytext + yyleng)) >> std::boolalpha >> yylval.boolv
#define SAVE_SHORT  yylval.shortv = str2short(std::string(yytext, yytext + yyleng - 1))
#define SAVE_INT    yylval.intv = str2int(std::string(yytext, yytext + yyleng))
#define SAVE_LONG   yylval.longv = str2long(std::string(yytext, yytext + yyleng - 1))
#define SAVE_INT128 yylval.int128v = str2int128(std::string(yytext, yytext + yyleng - 1))
#define SAVE_FLOAT  yylval.floatv = std::stof(std::string(yytext, yytext + yyleng))
#define SAVE_DOUBLE yylval.doublev = std::stod(std::string(yytext, yytext + yyleng))

std::string yyVexpLexError;
int yyInitToken = 0;

int yyWantIndent = 0; // hack to simulate one level of the "off side" rule
void wantIndent(bool f) {
  if (f) {
    ++yyWantIndent;
  } else if (yyWantIndent > 0) {
    --yyWantIndent;
  }
}
bool wantIndent() { return yyWantIndent > 0; }

std::vector<int> yyIndentStack;
void pushIndent() {
  yyIndentStack.push_back(yyWantIndent);
  yyWantIndent = 0;
}
void popIndent() {
  if(!yyIndentStack.empty()){
    yyWantIndent = *--yyIndentStack.end();
    yyIndentStack.pop_back();
  }
}

// The scanner keeps state from one token to the next: the start condition it
// is in (INITIAL, or inside a block comment), whether an indent is currently
// significant, and the stack of that for each bracket opened. A parse that
// ends early -- a syntax error, an exception out of a grammar action -- leaves
// all of it wherever the failure found it, and nothing used to reset it, so
// the next parse in the process inherited it: an unterminated block comment
// left every later input read as comment, and a class body cut short left
// later inputs with an indent token where none belongs.
//
// So the parser brackets every parse with these. pushLexerParseState saves
// the state and resets it to what a fresh process has; popLexerParseState
// puts the saved state back. Saving rather than just resetting is for the
// parse of an imported script, which runs nested inside its importer's parse
// and must hand the importer's state back when it is done.
struct LexerParseState {
  int              start;
  int              wantIndent;
  std::vector<int> indentStack;
};
std::vector<LexerParseState> yySavedLexerParseStates;

void pushLexerParseState() {
  LexerParseState s;
  s.start       = YY_START;
  s.wantIndent  = yyWantIndent;
  s.indentStack = yyIndentStack;
  yySavedLexerParseStates.push_back(s);

  BEGIN(0); // INITIAL -- which flex defines only after this prologue, as 0
  yyWantIndent = 0;
  yyIndentStack.clear();
}

void popLexerParseState() {
  if (yySavedLexerParseStates.empty()) {
    return;
  }
  const LexerParseState& s = yySavedLexerParseStates.back();
  BEGIN(s.start);
  yyWantIndent  = s.wantIndent;
  yyIndentStack = s.indentStack;
  yySavedLexerParseStates.pop_back();
}

// Give back the last n characters of the current match.
//
// The indentation rules below need one or two characters of lookahead to tell
// an indented line from a comment, and they used to ask flex for it as
// trailing context. Variable trailing context makes flex carry a backtracking
// state stack -- one entry per character scanned while matching a token -- in
// a buffer it allocates once at (YY_BUF_SIZE + 2) states and never grows, so
// scanning a token longer than that wrote past the end of it. Matching the
// lookahead and handing it back leaves no rule with trailing context, and flex
// emits no such buffer at all, so the length of a token is bounded only by the
// input. yyless rewinds yyleng and, for any newline among the characters it
// gives back, yylineno -- both of which YY_USER_ACTION has already used, so
// the token's line and end column are restated here once they are right.
#define pushBackLookahead(n)                                   \
  do {                                                         \
    yyless(yyleng - (n));                                      \
    yylloc.first_line = yylloc.last_line = yylineno;           \
    yylloc.last_column = yylloc.first_column + yyleng - 1;     \
  } while (false)

std::string* identifier(const char* b, const char* e) {
  if ((b+1) == e && *b == '_') {
    return hobbes::autorelease(new std::string(hobbes::freshName()));
  } else {
    return hobbes::autorelease(new std::string(b, e));
  }
}
#line 842 "hexpr.lex.C"

#line 844 "hexpr.lex.C"

#define INITIAL 0
#define BLOCK_COMMENT 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 174 "hexpr.l"



#line 178 "hexpr.l"
  /* simulate multiple start symbols in our grammar by supporting a distinguished prefix token to switch on pseudo-start symbol productions */
  if (yyInitToken) {
    int r = yyInitToken;
    yyInitToken = 0;
    return r;
  }


#line 1075 "hexpr.lex.C"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 282 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 393 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 186 "hexpr.l"
{ yycolumn = 1; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 187 "hexpr.l"
{ }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 188 "hexpr.l"
{ pushBackLookahead(1); yycolumn = 2; if (wantIndent()) { return TINDENT; } }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 189 "hexpr.l"
{ pushBackLookahead(2); yycolumn = 2; if (wantIndent()) { return TINDENT; } }
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 190 "hexpr.l"
{ yycolumn = 2; if (wantIndent()) { return TINDENT; } }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 191 "hexpr.l"
{               if (wantIndent()) { return TINDENT; } }
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 192 "hexpr.l"
{ yycolumn = 2; if (wantIndent()) { return TINDENT; } }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 193 "hexpr.l"
{               if (wantIndent()) { return TINDENT; } }
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 194 "hexpr.l"
{ yycolumn = 1; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 196 "hexpr.l"
{ BEGIN(BLOCK_COMMENT); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 197 "hexpr.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 198 "hexpr.l"
{ yycolumn = 1; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 199 "hexpr.l"
{ }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 201 "hexpr.l"
{ return TOPTION; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 202 "hexpr.l"
{ return TMODULE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 203 "hexpr.l"
{ return TWHERE; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 204 "hexpr.l"
{ return TIMPORT; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 205 "hexpr.l"
{ return TTYPE; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 206 "hexpr.l"
{ return TDATA; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 207 "hexpr.l"
{ wantIndent(true); return TCLASS; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 208 "hexpr.l"
{ wantIndent(true); return TINST; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 209 "hexpr.l"
{ return TEXISTS; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 210 "hexpr.l"
{ return TUNSAFE; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 211 "hexpr.l"
{ return TSAFE; } 
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 213 "hexpr.l"
{ return TASSIGN; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 214 "hexpr.l"
{ return TEQUALS; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 215 "hexpr.l"
{ return TASSUMP; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 216 "hexpr.l"
{ return TCSTARROW; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 217 "hexpr.l"
{ return TPARROW; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 218 "hexpr.l"
{ return TCOLON; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 219 "hexpr.l"
{ return TARROW; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 220 "hexpr.l"
{ return TEQUIV; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 221 "hexpr.l"
{ return TEQ; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 222 "hexpr.l"
{ return TCIEQ; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 223 "hexpr.l"
{ return TNEQ; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 224 "hexpr.l"
{ return TLT; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 225 "hexpr.l"
{ return TLTE; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 226 "hexpr.l"
{ return TGT; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 227 "hexpr.l"
{ return TGTE; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 228 "hexpr.l"
{ return TNOT; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 229 "hexpr.l"
{ return TNOT; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 230 "hexpr.l"
{ return TLET; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 231 "hexpr.l"
{ return TCASE; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 232 "hexpr.l"
{ return TDEFAULT; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 233 "hexpr.l"
{ return TMATCH; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 234 "hexpr.l"
{ return TMATCHES; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 235 "hexpr.l"
{ return TPARSE; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 236 "hexpr.l"
{ return TWITH; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 237 "hexpr.l"
{ return TOF; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 238 "hexpr.l"
{ return TAND; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 239 "hexpr.l"
{ return TOR; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 240 "hexpr.l"
{ return TIF; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 241 "hexpr.l"
{ return TTHEN; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 242 "hexpr.l"
{ return TELSE; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 243 "hexpr.l"
{ SAVE_BOOL; return TBOOL; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 244 "hexpr.l"
{ SAVE_BOOL; return TBOOL; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 245 "hexpr.l"
{ return TIN; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 246 "hexpr.l"
{ return TPACK; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 247 "hexpr.l"
{ return TUNPACK; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 248 "hexpr.l"
{ return TDO; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 249 "hexpr.l"
{ return TRETURN; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 251 "hexpr.l"
{ return TLPRAGMA; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 252 "hexpr.l"
{ return TRPRAGMA; }   
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 254 "hexpr.l"
{ pushIndent(); return TLPAREN; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 255 "hexpr.l"
{ popIndent();  return TRPAREN; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 256 "hexpr.l"
{ pushIndent(); return TLBRACKET; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 257 "hexpr.l"
{ popIndent();  return TRBRACKET; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 258 "hexpr.l"
{ pushIndent(); return TLBRACE; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 259 "hexpr.l"
{ popIndent();  return TRBRACE; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 261 "hexpr.l"
{ return TBAR; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 262 "hexpr.l"
{ return TCOMMA; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 263 "hexpr.l"
{ return TSEMICOLON; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 264 "hexpr.l"
{ return TAPPEND; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 265 "hexpr.l"
{ return TPLUS; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 266 "hexpr.l"
{ return TMINUS; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 267 "hexpr.l"
{ return TTIMES; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 268 "hexpr.l"
{ return TDIVIDE; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 269 "hexpr.l"
{ return TREM; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 270 "hexpr.l"
{ return TFN; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 271 "hexpr.l"
{ return TFNL; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 272 "hexpr.l"
{ return TCOMPOSE; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 273 "hexpr.l"
{ return TDOT; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 274 "hexpr.l"
{ return TUPTO; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 275 "hexpr.l"
{ return TCARET; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 276 "hexpr.l"
{ return TAT; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 277 "hexpr.l"
{ return TDOLLAR; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 278 "hexpr.l"
{ return TQUESTION; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 279 "hexpr.l"
{ SAVE_STR;    return (hobbes::str::unescape(hobbes::str::trimq(*yylval.string, '\'')).size() <= 1) ? TCHAR : TREGEX; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 280 "hexpr.l"
{ return TSQUOTE; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 281 "hexpr.l"
{ return TEQUOTE; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 282 "hexpr.l"
{ SAVE_STR;    return TBYTE; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 283 "hexpr.l"
{ SAVE_STR;    return TBYTES; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 284 "hexpr.l"
{ SAVE_IDENT;  return TIDENT; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 285 "hexpr.l"
{ SAVE_STR;    return TTUPSECTION; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 286 "hexpr.l"
{ SAVE_FLOAT;  return TFLOAT; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 287 "hexpr.l"
{ SAVE_DOUBLE; return TDOUBLE; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 288 "hexpr.l"
{ SAVE_DOUBLE; yylval.doublev *= 0.01; return TDOUBLE; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 289 "hexpr.l"
{ SAVE_INT128; return TINT128; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 290 "hexpr.l"
{ SAVE_LONG;   return TLONG; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 291 "hexpr.l"
{ SAVE_SHORT;  return TSHORT; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 292 "hexpr.l"
{ SAVE_INT;    return TINT; }
	YY_BREAK
case 102:
/* rule 102 can match eol */
YY_RULE_SETUP
#line 293 "hexpr.l"
{ SAVE_STR;    return TSTRING; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 295 "hexpr.l"
{ SAVE_STR;    return TTIMEINTERVAL; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 296 "hexpr.l"
{ SAVE_STR;    return TTIMEINTERVAL; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 297 "hexpr.l"
{ SAVE_STR;    return TTIMEINTERVAL; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 298 "hexpr.l"
{ SAVE_STR;    return TTIMEINTERVAL; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 299 "hexpr.l"
{ SAVE_STR;    return TTIMEINTERVAL; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 300 "hexpr.l"
{ SAVE_STR;    return TTIMEINTERVAL; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 301 "hexpr.l"
{ SAVE_STR;    return TTIMEINTERVAL; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 302 "hexpr.l"
{ SAVE_STR;    return TTIMEINTERVAL; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 303 "hexpr.l"
{ SAVE_STR;    return TTIMEINTERVAL; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 305 "hexpr.l"
{ SAVE_STR; return TTIME; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 306 "hexpr.l"
{ SAVE_STR; return TTIME; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 307 "hexpr.l"
{ SAVE_STR; return TTIME; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 308 "hexpr.l"
{ SAVE_STR; return TTIME; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 310 "hexpr.l"
{ SAVE_STR; return TDATETIME; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 311 "hexpr.l"
{ SAVE_STR; return TDATETIME; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 312 "hexpr.l"
{ SAVE_STR; return TDATETIME; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 313 "hexpr.l"
{ SAVE_STR; return TDATETIME; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 314 "hexpr.l"
{ SAVE_STR; return TDATETIME; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 316 "hexpr.l"
{ yyVexpLexError = "Unknown character: " + std::string(yytext); yyterminate(); if (false) { yyrealloc(0, 0); yyunput(0, 0); } }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 318 "hexpr.l"
ECHO;
	YY_BREAK
#line 1760 "hexpr.lex.C"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(BLOCK_COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 282 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 282 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 281);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 318 "hexpr.l"

#pragma GCC diagnostic pop


