#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wold-style-cast"
#pragma GCC diagnostic ignored "-Wunused-label"
#pragma GCC diagnostic ignored "-Wunused-function"
#pragma GCC diagnostic ignored "-Wall"
#line 2 "hexpr.lex.C"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdeprecated-register"
#pragma clang diagnostic ignored "-Wold-style-cast"
#pragma clang diagnostic ignored "-Wunused-label"
#pragma clang diagnostic ignored "-Wunused-function"
#pragma clang diagnostic ignored "-Wall"
#endif

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 113
#define YY_END_OF_BUFFER 114
static yyconst short int yy_acclist[337] =
    {   0,
      114,  112,  113,    2,  112,  113,    1,  113,    2,  112,
      113,    2,  112,  113,   35,  112,  113,  112,  113,   78,
      112,  113,   71,  112,  113,   81,  112,  113,   57,  112,
      113,   58,  112,  113,   69,  112,  113,   67,  112,  113,
       64,  112,  113,   68,  112,  113,   74,  112,  113,   70,
      112,  113,   92,  112,  113,   92,  112,  113,   25,  112,
      113,   65,  112,  113,   31,  112,  113,   21,  112,  113,
       33,  112,  113,   79,  112,  113,   77,  112,  113,   85,
      112,  113,   59,  112,  113,   72,  112,  113,   60,  112,
      113,   76,  112,  113,   82,  112,  113,   85,  112,  113,

       85,  112,  113,   85,  112,  113,   85,  112,  113,   85,
      112,  113,   85,  112,  113,   85,  112,  113,   85,  112,
      113,   85,  112,  113,   85,  112,  113,   85,  112,  113,
       85,  112,  113,   85,  112,  113,   85,  112,  113,   85,
      112,  113,   61,  112,  113,   63,  112,  113,   62,  112,
      113,   29,  112,  113,   11,  113,   10,  113,   11,  113,
        5,    3,    6,    4,   30,   93,   66,   26,   75,    8,
       92,   90,   91,   99,   98,   97,   96,   22,   24,   20,
       32,   27,   23,   34,   85,   85,   85,   85,   85,   85,
       55,   85,   85,   85,   85,   47,   85,   85,   52,   85,

       85,   85,   85,   85,   44,   85,   46,   85,   85,   85,
       85,   85,   85,   85,   85,   85,    9,   73,   93,   80,
        7,   88,   92,   94,   95,   28,   45,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   37,   85,   85,
       85,   36,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   86,   89,   87,   92,   83,  102,  100,   84,
       38,   85,   85,   16,   85,   85,   49,   85,   85,   85,
       85,   85,   85,   85,   53,   85,   85,   85,   48,   85,
       50,   85,   15,   85,   85,   85,   43,   85,   92,  103,
      101,   17,   85,   85,   85,   51,   85,   85,   85,   40,

       85,   85,   42,   85,   85,   85,   13,   85,   85,   19,
       85,   14,   85,   85,   85,   12,   85,   56,   85,   54,
       85,   39,   85,   85,   41,   85,  104,   18,   85,  107,
      105,  106,  108,  109,  110,  111
    } ;

static yyconst short int yy_accept[257] =
    {   0,
        1,    1,    1,    1,    1,    2,    4,    7,    9,   12,
       15,   18,   20,   23,   26,   29,   32,   35,   38,   41,
       44,   47,   50,   53,   56,   59,   62,   65,   68,   71,
       74,   77,   80,   83,   86,   89,   92,   95,   98,  101,
      104,  107,  110,  113,  116,  119,  122,  125,  128,  131,
      134,  137,  140,  143,  146,  149,  152,  155,  157,  159,
      161,  162,  163,  164,  165,  165,  166,  166,  167,  167,
      167,  167,  168,  169,  170,  170,  171,  171,  171,  172,
      173,  174,  174,  175,  176,  177,  178,  178,  178,  179,
      180,  181,  182,  183,  184,  185,  186,  187,  188,  189,

      190,  191,  193,  194,  195,  196,  198,  199,  201,  202,
      203,  204,  205,  207,  209,  210,  211,  212,  213,  214,
      215,  216,  217,  218,  219,  219,  220,  220,  221,  221,
      221,  222,  223,  224,  224,  224,  224,  224,  224,  225,
      226,  226,  227,  229,  230,  231,  232,  233,  234,  235,
      236,  237,  238,  240,  241,  242,  244,  245,  246,  247,
      248,  249,  250,  251,  252,  253,  254,  255,  256,  257,
      257,  258,  259,  259,  260,  261,  263,  264,  266,  267,
      269,  270,  271,  272,  273,  274,  275,  277,  278,  279,
      281,  283,  285,  286,  287,  289,  289,  290,  291,  292,

      294,  295,  296,  298,  299,  300,  302,  303,  305,  306,
      307,  309,  309,  309,  310,  312,  314,  315,  316,  318,
      320,  322,  322,  322,  324,  325,  327,  327,  328,  330,
      330,  330,  331,  331,  331,  331,  331,  332,  332,  332,
      332,  332,  332,  333,  334,  334,  334,  335,  335,  335,
      335,  336,  336,  336,  337,  337
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    1,    9,   10,    1,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   29,   29,   29,   29,   30,
       31,   31,   31,   31,   31,   32,   31,   31,   31,   31,
       31,   31,   33,   34,   31,   31,   31,   35,   31,   31,
       36,   37,   38,   39,   31,   40,   41,   29,   42,   43,

       44,   45,   31,   46,   47,   31,   48,   49,   50,   51,
       52,   53,   31,   54,   55,   56,   57,   31,   58,   59,
       60,   31,   61,   62,   63,   64,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[65] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        2,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        3,    1,    1,    1,    1,    1,    1,    1,    3,    3,
        3,    3,    3,    3,    3,    1,    1,    1,    1,    1,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        1,    1,    1,    1
    } ;

static yyconst short int yy_base[262] =
    {   0,
        0,    0,   62,   63,  374,  375,  375,   65,   66,  355,
      347,   61,  375,  375,  334,  375,  375,  375,  355,  375,
      343,   60,   56,   81,   38,   57,  375,   66,   59,  343,
      375,  375,    0,  375,  375,  375,  375,  375,  316,   45,
       48,   44,  325,   45,  321,   63,  312,   63,  322,  318,
       65,  310,   41,  375,  375,  375,  375,  375,  375,  341,
      375,  375,  375,  375,  353,  375,   97,  375,  104,   95,
      347,  375,  375,  375,  100,  375,  354,   89,  122,  375,
      375,  125,  315,  303,   82,  375,  299,  130,  375,  375,
      375,  375,  328,  375,  375,    0,  309,  296,  309,  293,

      303,    0,  292,  299,  296,    0,  291,  288,  286,  285,
      297,  283,    0,    0,   81,  282,  293,  279,  282,  281,
      289,  276,  375,  375,  125,  139,  145,  375,  143,  328,
      375,  167,  158,  163,  165,  270,  272,  277,  375,  375,
      172,  375,    0,  283,  271,  284,  283,  279,  267,  266,
      268,  263,    0,  276,  260,    0,  268,  260,  257,  262,
      268,  267,  269,  255,  262,  169,  375,  375,  179,  183,
      375,  375,  253,  375,  198,    0,  251,    0,  248,    0,
      248,  259,  248,  260,  254,  250,    0,  254,  243,    0,
        0,    0,  254,  251,    0,  200,  277,  271,  375,    0,

      243,  236,    0,  227,  175,  167,  161,    0,  147,  143,
        0,  202,  204,  109,    0,    0,  119,  103,    0,    0,
        0,  139,  209,    0,  108,    0,  211,  131,    0,  213,
      215,  105,  217,  224,  226,  228,  230,  106,  232,  234,
      236,  238,  375,  104,  240,  242,  104,  244,  246,  248,
      250,  252,  254,  375,  375,  275,  278,  281,   71,  284,
      287
    } ;

static yyconst short int yy_def[262] =
    {   0,
      255,    1,  256,  256,  255,  255,  255,  255,  255,  255,
      255,  257,  255,  255,  258,  255,  255,  255,  255,  255,
      255,  255,  255,  255,   24,  255,  255,  255,  255,  255,
      255,  255,  259,  255,  255,  255,  255,  255,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  257,  255,  260,  258,
      258,  255,  255,  255,  255,  255,  261,  255,   24,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  259,  259,  259,  259,  259,

      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  255,  255,  257,  257,  260,  255,  255,  261,
      255,  255,   79,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  255,  255,  255,  133,  255,
      255,  255,  255,  255,  255,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  255,  169,  255,  255,  259,

      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  255,  255,  259,  259,  259,  259,  259,  259,  259,
      259,  255,  255,  259,  259,  259,  255,  255,  259,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,    0,  255,  255,  255,  255,  255,
      255
    } ;

static yyconst short int yy_nxt[440] =
    {   0,
        6,    7,    8,    7,    9,   10,   11,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   33,
       33,   33,   33,   33,   33,   34,   35,   36,   37,   38,
       39,   40,   41,   42,   43,   33,   44,   33,   45,   46,
       47,   48,   49,   50,   33,   51,   52,   53,   33,   33,
       54,   55,   56,   57,   59,   59,   61,   63,   68,   76,
       62,   64,  255,   96,   77,   60,   60,   74,   89,   75,
       75,   90,   91,   93,   94,   98,  121,  122,  100,  106,
       92,  101,  103,   99,  107,  108,  255,   69,   78,  102,

       79,   79,  104,  110,   68,  128,   67,  113,  132,  132,
      117,  126,   80,   81,  111,   82,  114,  129,  118,   75,
       75,  248,  157,   83,  119,  245,   84,  240,  138,   80,
       85,   71,   68,   69,  158,   86,  139,   87,  234,   88,
      127,  133,  133,  134,  135,  135,   68,   67,  231,  141,
      141,  229,  126,  135,  135,  227,  255,  226,  141,  141,
      225,   69,  166,  166,  224,  135,  135,  135,  135,  135,
      141,  141,  141,  141,  141,   69,  167,  169,  169,  255,
      255,  127,  170,  170,  171,  171,  132,  132,  166,  166,
      221,  175,  175,  171,  171,  196,  168,  220,  197,  197,

      175,  175,  198,  198,  219,  171,  171,  171,  171,  171,
      218,  168,  175,  175,  175,  175,  175,  141,  141,  212,
      212,  222,  222,  223,  223,  217,  141,  141,  228,  228,
      230,  230,  232,  232,  233,  233,  235,  235,  141,  141,
      141,  141,  141,  236,  236,  237,  237,  238,  238,  239,
      239,  241,  241,  242,  242,  243,  243,  244,  244,  246,
      246,  247,  247,  249,  249,  250,  250,  251,  251,  252,
      252,  253,  253,  254,  254,   58,   58,   58,   67,   67,
       67,   70,  216,   70,  125,  125,  125,  130,  130,  130,
      215,  214,  213,  255,  211,  210,  209,  208,  207,  206,

      205,  204,  203,  202,  201,  200,  199,  195,  194,  193,
      192,  191,  190,  189,  188,  187,  186,  185,  184,  183,
      182,  181,  180,  179,  178,  177,  176,  174,  173,  172,
      131,  165,  164,  163,  162,  161,  160,  159,  156,  155,
      154,  153,  152,  151,  150,  149,  148,  147,  146,  145,
      144,  143,  142,  140,  137,  136,  131,   70,  124,  123,
      120,  116,  115,  112,  109,  105,   97,   95,   73,   72,
       71,   66,   65,  255,    5,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,

      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255
    } ;

static yyconst short int yy_chk[440] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    4,    8,    9,   12,   23,
        8,    9,   25,  259,   23,    3,    4,   22,   26,   22,
       22,   26,   28,   29,   29,   40,   53,   53,   41,   44,
       28,   41,   42,   40,   44,   44,   25,   12,   24,   41,

       24,   24,   42,   46,   67,   70,   69,   48,   78,   78,
       51,   69,   24,   24,   46,   24,   48,   75,   51,   75,
       75,  247,  115,   24,   51,  244,   24,  238,   85,   24,
       24,   70,  125,   67,  115,   24,   85,   24,  232,   24,
       69,   79,   79,   79,   82,   82,  126,  127,  228,   88,
       88,  225,  127,   82,   82,  222,   79,  218,   88,   88,
      217,  125,  129,  129,  214,   82,   82,   82,   82,   82,
       88,   88,   88,   88,   88,  126,  132,  133,  133,  133,
       79,  127,  134,  134,  135,  135,  132,  132,  166,  166,
      210,  141,  141,  135,  135,  169,  132,  209,  169,  169,

      141,  141,  170,  170,  207,  135,  135,  135,  135,  135,
      206,  132,  141,  141,  141,  141,  141,  175,  175,  196,
      196,  212,  212,  213,  213,  205,  175,  175,  223,  223,
      227,  227,  230,  230,  231,  231,  233,  233,  175,  175,
      175,  175,  175,  234,  234,  235,  235,  236,  236,  237,
      237,  239,  239,  240,  240,  241,  241,  242,  242,  245,
      245,  246,  246,  248,  248,  249,  249,  250,  250,  251,
      251,  252,  252,  253,  253,  256,  256,  256,  257,  257,
      257,  258,  204,  258,  260,  260,  260,  261,  261,  261,
      202,  201,  198,  197,  194,  193,  189,  188,  186,  185,

      184,  183,  182,  181,  179,  177,  173,  165,  164,  163,
      162,  161,  160,  159,  158,  157,  155,  154,  152,  151,
      150,  149,  148,  147,  146,  145,  144,  138,  137,  136,
      130,  122,  121,  120,  119,  118,  117,  116,  112,  111,
      110,  109,  108,  107,  105,  104,  103,  101,  100,   99,
       98,   97,   93,   87,   84,   83,   77,   71,   65,   60,
       52,   50,   49,   47,   45,   43,   39,   30,   21,   19,
       15,   11,   10,    5,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,

      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "hexpr.l"
#define INITIAL 0
#line 2 "hexpr.l"
#ifdef __clang__
#pragma clang diagnostic ignored "-Wdeprecated-register"
#endif

int yycolumn = 1;

#define YY_USER_ACTION \
  yylloc.first_line = yylloc.last_line = yylineno; \
  yylloc.first_column = yycolumn; yylloc.last_column = yycolumn+yyleng-1; \
  yycolumn += yyleng;

#include <hobbes/lang/module.H>
#include <hobbes/lang/expr.H>
#include <hobbes/lang/pat/pattern.H>
#include <hobbes/util/autorelease.H>
#include <hobbes/parse/grammar.H>
#include <hobbes/read/pgen/hexpr.parse.H>
#include <string>
#include <iostream>

#define SAVE_STR    yylval.string = hobbes::autorelease(new std::string(yytext, yytext + yyleng))
#define SAVE_IDENT  yylval.string = identifier(yytext, yytext + yyleng)
#define SAVE_BOOL   std::istringstream(std::string(yytext, yytext + yyleng)) >> std::boolalpha >> yylval.boolv
#define SAVE_SHORT  yylval.shortv = (short)std::stoi(std::string(yytext, yytext + yyleng))
#define SAVE_INT    yylval.intv = std::stoi(std::string(yytext, yytext + yyleng))
#define SAVE_LONG   yylval.longv = std::stol(std::string(yytext, yytext + yyleng - 1))
#define SAVE_FLOAT  yylval.floatv = std::stof(std::string(yytext, yytext + yyleng))
#define SAVE_DOUBLE yylval.doublev = std::stod(std::string(yytext, yytext + yyleng))

std::string yyVexpLexError;
int yyInitToken = 0;

int yyWantIndent = 0; // hack to simulate one level of the "off side" rule
void wantIndent(bool f) {
  if (f) {
    ++yyWantIndent;
  } else if (yyWantIndent > 0) {
    --yyWantIndent;
  }
}
bool wantIndent() { return yyWantIndent > 0; }

std::string* identifier(const char* b, const char* e) {
  if ((b+1) == e && *b == '_') {
    return hobbes::autorelease(new std::string(hobbes::freshName()));
  } else {
    return hobbes::autorelease(new std::string(b, e));
  }
}
#define BLOCK_COMMENT 1

#line 650 "hexpr.lex.C"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 57 "hexpr.l"



  /* simulate multiple start symbols in our grammar by supporting a distinguished prefix token to switch on pseudo-start symbol productions */
  if (yyInitToken) {
    int r = yyInitToken;
    yyInitToken = 0;
    return r;
  }


#line 813 "hexpr.lex.C"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 256 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 375 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 68 "hexpr.l"
{ yycolumn = 1; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 69 "hexpr.l"
{ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 70 "hexpr.l"
{ yycolumn = 2; if (wantIndent()) { return TINDENT; } }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 71 "hexpr.l"
{               if (wantIndent()) { return TINDENT; } }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 72 "hexpr.l"
{ yycolumn = 2; if (wantIndent()) { return TINDENT; } }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 73 "hexpr.l"
{               if (wantIndent()) { return TINDENT; } }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 74 "hexpr.l"
{ yycolumn = 1; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 75 "hexpr.l"
{ BEGIN(BLOCK_COMMENT); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 76 "hexpr.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 77 "hexpr.l"
{ yycolumn = 1; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 78 "hexpr.l"
{ }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 80 "hexpr.l"
{ return TMODULE; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 81 "hexpr.l"
{ return TWHERE; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 82 "hexpr.l"
{ return TIMPORT; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 83 "hexpr.l"
{ return TTYPE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 84 "hexpr.l"
{ return TDATA; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 85 "hexpr.l"
{ wantIndent(true); return TCLASS; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 86 "hexpr.l"
{ wantIndent(true); return TINST; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 87 "hexpr.l"
{ return TEXISTS; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 89 "hexpr.l"
{ return TASSIGN; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 90 "hexpr.l"
{ return TEQUALS; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 91 "hexpr.l"
{ return TASSUMP; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 92 "hexpr.l"
{ return TCSTARROW; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 93 "hexpr.l"
{ return TPARROW; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 94 "hexpr.l"
{ return TCOLON; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 95 "hexpr.l"
{ return TARROW; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 96 "hexpr.l"
{ return TEQUIV; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 97 "hexpr.l"
{ return TEQ; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 98 "hexpr.l"
{ return TCIEQ; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 99 "hexpr.l"
{ return TNEQ; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 100 "hexpr.l"
{ return TLT; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 101 "hexpr.l"
{ return TLTE; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 102 "hexpr.l"
{ return TGT; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 103 "hexpr.l"
{ return TGTE; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 104 "hexpr.l"
{ return TNOT; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 105 "hexpr.l"
{ return TNOT; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 106 "hexpr.l"
{ return TLET; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 107 "hexpr.l"
{ return TCASE; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 108 "hexpr.l"
{ return TDEFAULT; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 109 "hexpr.l"
{ return TMATCH; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 110 "hexpr.l"
{ return TMATCHES; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 111 "hexpr.l"
{ return TPARSE; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 112 "hexpr.l"
{ return TWITH; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 113 "hexpr.l"
{ return TOF; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 114 "hexpr.l"
{ return TAND; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 115 "hexpr.l"
{ return TOR; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 116 "hexpr.l"
{ return TIF; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 117 "hexpr.l"
{ return TTHEN; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 118 "hexpr.l"
{ return TELSE; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 119 "hexpr.l"
{ SAVE_BOOL; return TBOOL; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 120 "hexpr.l"
{ SAVE_BOOL; return TBOOL; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 121 "hexpr.l"
{ return TIN; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 122 "hexpr.l"
{ return TPACK; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 123 "hexpr.l"
{ return TUNPACK; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 124 "hexpr.l"
{ return TDO; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 125 "hexpr.l"
{ return TRETURN; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 126 "hexpr.l"
{ return TLPAREN; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 127 "hexpr.l"
{ return TRPAREN; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 128 "hexpr.l"
{ return TLBRACKET; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 129 "hexpr.l"
{ return TRBRACKET; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 130 "hexpr.l"
{ return TLBRACE; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 131 "hexpr.l"
{ return TRBRACE; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 132 "hexpr.l"
{ return TBAR; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 133 "hexpr.l"
{ return TCOMMA; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 134 "hexpr.l"
{ return TSEMICOLON; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 135 "hexpr.l"
{ return TAPPEND; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 136 "hexpr.l"
{ return TPLUS; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 137 "hexpr.l"
{ return TMINUS; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 138 "hexpr.l"
{ return TTIMES; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 139 "hexpr.l"
{ return TDIVIDE; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 140 "hexpr.l"
{ return TREM; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 141 "hexpr.l"
{ return TFN; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 142 "hexpr.l"
{ return TCOMPOSE; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 143 "hexpr.l"
{ return TDOT; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 144 "hexpr.l"
{ return TUPTO; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 145 "hexpr.l"
{ return TCARET; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 146 "hexpr.l"
{ return TAT; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 147 "hexpr.l"
{ return TDOLLAR; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 148 "hexpr.l"
{ return TQUESTION; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 149 "hexpr.l"
{ SAVE_STR;    return (hobbes::str::unescape(hobbes::str::trimq(*yylval.string, '\'')).size() <= 1) ? TCHAR : TREGEX; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 150 "hexpr.l"
{ return TSQUOTE; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 151 "hexpr.l"
{ return TEQUOTE; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 152 "hexpr.l"
{ SAVE_STR;    return TBYTE; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 153 "hexpr.l"
{ SAVE_STR;    return TBYTES; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 154 "hexpr.l"
{ SAVE_IDENT;  return TIDENT; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 155 "hexpr.l"
{ SAVE_STR;    return TTUPSECTION; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 156 "hexpr.l"
{ SAVE_FLOAT;  return TFLOAT; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 157 "hexpr.l"
{ SAVE_DOUBLE; return TDOUBLE; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 158 "hexpr.l"
{ SAVE_DOUBLE; yylval.doublev *= 0.01; return TDOUBLE; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 159 "hexpr.l"
{ SAVE_LONG;   return TLONG; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 160 "hexpr.l"
{ SAVE_SHORT;  return TSHORT; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 161 "hexpr.l"
{ SAVE_INT;    return TINT; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 162 "hexpr.l"
{ SAVE_STR;    return TSTRING; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 164 "hexpr.l"
{ SAVE_STR;    return TTIMEINTERVAL; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 165 "hexpr.l"
{ SAVE_STR;    return TTIMEINTERVAL; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 166 "hexpr.l"
{ SAVE_STR;    return TTIMEINTERVAL; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 167 "hexpr.l"
{ SAVE_STR;    return TTIMEINTERVAL; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 168 "hexpr.l"
{ SAVE_STR;    return TTIMEINTERVAL; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 169 "hexpr.l"
{ SAVE_STR;    return TTIMEINTERVAL; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 170 "hexpr.l"
{ SAVE_STR;    return TTIMEINTERVAL; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 171 "hexpr.l"
{ SAVE_STR;    return TTIMEINTERVAL; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 172 "hexpr.l"
{ SAVE_STR;    return TTIMEINTERVAL; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 174 "hexpr.l"
{ SAVE_STR; return TTIME; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 175 "hexpr.l"
{ SAVE_STR; return TTIME; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 176 "hexpr.l"
{ SAVE_STR; return TTIME; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 177 "hexpr.l"
{ SAVE_STR; return TTIME; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 179 "hexpr.l"
{ SAVE_STR; return TDATETIME; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 180 "hexpr.l"
{ SAVE_STR; return TDATETIME; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 181 "hexpr.l"
{ SAVE_STR; return TDATETIME; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 182 "hexpr.l"
{ SAVE_STR; return TDATETIME; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 183 "hexpr.l"
{ SAVE_STR; return TDATETIME; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 185 "hexpr.l"
{ yyVexpLexError = "Unknown character: " + std::string(yytext); yyterminate(); if (false) { yy_flex_realloc(0, 0); yyunput(0, 0); } }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 187 "hexpr.l"
ECHO;
	YY_BREAK
#line 1469 "hexpr.lex.C"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(BLOCK_COMMENT):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 256 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 256 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 255);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}
#endif /* YY_NO_INPUT */

#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 187 "hexpr.l"

#pragma GCC diagnostic pop
