# Embed a directory's *.hob boot scripts in a header, as byte arrays:
#
#   cmake -DBOOT_DIR=<dir of *.hob> -DOUTPUT=<header> -P EmbedBootScripts.cmake
#
# The header defines 'module_defs', a null-terminated array of the scripts'
# contents in file name order (the order they are compiled in, so the order
# they may depend on one another in), and 'module_lens', their lengths. It has
# no include guard and no namespace: it is meant to be included once, inside the
# namespace of the code that compiles the scripts.
#
# The build runs this whenever a script changes, so that what is embedded is
# always what is in the source tree. It is CMake rather than xxd, which did this
# job when the header was checked in, because xxd comes with vim and the build
# should not need an editor installed.

if(NOT BOOT_DIR OR NOT OUTPUT)
  message(FATAL_ERROR "EmbedBootScripts: BOOT_DIR and OUTPUT are required")
endif()

file(GLOB scripts "${BOOT_DIR}/*.hob")
list(SORT scripts)
if(NOT scripts)
  message(FATAL_ERROR "EmbedBootScripts: no *.hob files in ${BOOT_DIR}")
endif()

# 16 bytes to a row
string(REPEAT "[0-9a-f]" 32 row)

set(arrays "")
set(defs "")
set(lens "")
foreach(script IN LISTS scripts)
  get_filename_component(name "${script}" NAME)
  string(MAKE_C_IDENTIFIER "${name}" id)
  set(id "boot_${id}")

  file(READ "${script}" hex HEX)
  string(LENGTH "${hex}" len)
  math(EXPR len "${len} / 2")

  string(REGEX REPLACE "(${row})" "\\1\n" hex "${hex}")
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," hex "${hex}")
  string(REGEX REPLACE "\n$" "" hex "${hex}")
  string(REPLACE "\n" "\n  " hex "${hex}")

  # the terminator is not counted in the length; it is there so that an empty
  # script does not make an empty array
  string(APPEND arrays "// ${name}\nstatic const unsigned char ${id}[] = {\n  ${hex}\n  0x00\n};\n\n")
  string(APPEND defs "  ${id},\n")
  string(APPEND lens "  ${len}u,\n")
endforeach()

set(content "// generated by cmake/EmbedBootScripts.cmake from the *.hob boot scripts --\n// edit those, not this\n\n")
string(APPEND content "${arrays}")
string(APPEND content "static const unsigned char* const module_defs[] = {\n${defs}  nullptr\n};\n\n")
string(APPEND content "static const unsigned int module_lens[] = {\n${lens}  0u\n};\n")

file(WRITE "${OUTPUT}" "${content}")
